### ISSUE TITLE
Units in code from `pint` to `units`

### ISSUE THREAD

**Issue by andped10** [easyscience/core#12]
Seems like we are relying on `pint` to handle units.

We might eventually want to move towards `units` to get closer to how things are done in scipp.

**Comment by rozyczko** [comment]
Do you mean `Unit` from scipp.core?

**Comment by andped10** [comment]
I am not sure what I mean ;)  I have not looked into it carefully.  My point being that we might want to align EasyScience with Scipp as a part of our v1 work.

However I would think it was desirable if we can get the functionality from `scipp.core`

**Comment by damskii9992** [comment]
Can this issue be closed based on #19 ?
