### ISSUE TITLE
Add test for minimizers and confirm that DFO is working

### ISSUE THREAD

**Issue by andped10** [easyscience/core#22]
Add test for minimizer LM and base

When working on EasyReflectometry I was not able to get the DFO minimizer to work and it seems to be a problem with EasyScience.  We should add tests for each of the minimizers in EasyScience.  Currently we only test the factory and Fitter but not the different minimizers.

**Comment by damskii9992** [comment]
It turns out we do not even test the Fitter correctly, as all the minimizers are currently broken. The PR should however fix this bug.
