### ISSUE TITLE
Division by zero potentially crashes minimizers

### ISSUE THREAD

**Issue by damskii9992** [easyscience/core#37]
# The issue
With the implementation of arithmetic operations between `Parameter`s and `DescriptorNumber`s, and its usage in the dependent parameters, it is possible to have a division by zero during minimization runs. Since we don't want minimizers to crash, we have to somehow handle this rather than just raise a `ZeroDivisionError`.

# Discussion
Since we use Scipp to hold the values internally, it is natural to use the behavior of Scipp. In Scipp, division by zero returns `inf`, which is sensible for data-reduction in large workflows with big arrays of data with only few possible "bad" data points. 
This behavior adheres to the "IEEE 754" standard for floating-point arithmetic which is also followed by NumPy.
Bare python, however, raises a `ZeroDivisionError` when a number is divided by zero.

Now, the issue with following IEEE 754 and Scipp, is that multiplying `inf` with 0 yields `nan`, as does subtraction of `inf` from `inf` and having `nan` as values crashes minimizers. 

A possible solution, which is the one currently implemented, is to detect 0's and replace them with a very small number (currently 1e-9) for divisions. But other solutions/ideas are very welcome.

**Comment by rozyczko** [comment]
Can we just "clean" the `nan`s out from the final array?
```python
cleaned_data = np.where(np.isfinite(data), data, 0)
```
then send `cleaned_data` to the minimizer

**Comment by damskii9992** [comment]
Yes, this is a viable solution for the data arrays, potentially with a warning printed to the user that informs that NaN's and infinites are filtered out, but for the arithmetic operations between `Parameter`s and `DescriptorNumber`s, the value and the min/max can become NaN's as well, and unfortunately we can't just filter out those.

**Comment by henrikjacobsenfys** [comment]
I don't like the approach of replacing zero with a small but finite number. A division by zero should never happen in a physical model, and an error is in my opinion the correct response if it does happen while fitting. 

Zero divided by zero (or zero multiplied by infinity) might of course give a finite number, as in sin(x)/x when x=0. However, I think that in such cases, it's the job of whoever writes the function that is being fitted to ensure that it is handled properly.

The problem with replacing zero with a small but finite number (let's call it epsilon) is that it can cause very strange behaviour when fitting. There is a discontinuity when the parameter goes below epsilon, which can lead to weird chi^2 behaviour, which can lead to meaningless convergence of the fit. 

In my opinion, the solution is to give an error and try to tell the user exactly why the error happens. If they are calculating A/B and B tends to zero, then they need to either themselves put a lower limit on B, or figure out what they want their model to do when B=0.

**Comment by damskii9992** [comment]
I would tend to agree with you Henrik. If a user somehow encodes a model which causes a division by zero, it would be the users responsibility to add an infinitesimal in the correct place to avoid this division. The user would also know the size of the value in question and could thus use a small enough infinitesimal. 
I will change the implementation to raise a `ZeroDivisionError` instead.
