### ISSUE TITLE
Invalid escape sequence in docstring

### ISSUE THREAD

**Issue by jl-wynen** [easyscience/core#88]
There are invalid escape sequences in a docstring here: https://github.com/EasyScience/EasyScience/blob/a6d93795c396eb2c843d162908d636cbfe4e8a36/src/easyscience/Datasets/xarray.py#L284 Namely `\|`.

To fix it, either use `\\|` or make the docstring a raw string literal.

Normally, this only raises a `DeprecationWarning` which often does not show up in the terminal. But in our tests, we treat warnings as errors. This makes Python raise `SyntaxError` here.

**Comment by AndrewSazonov** [comment]
Fixed in #90
